sudo: false
language: elixir
otp_release:
  - 20.1
elixir:
  - 1.6.0
cache:
  directories:
    - /home/travis/.mix/
    - _build
    - deps
script:
  - mix test
  - MIX_ENV=test mix dialyzer --halt-exit-status
